sonar.projectKey=jouzi5_hazelcast-nacos
sonar.organization=jouzi5
sonar.host.url=https://sonarcloud.io
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.source=8
sonar.sourceEncoding=UTF-8